# version: '1.0'

services:
# Alexa Cookie Proxy
  alexa-cookie:
    container_name: alexa-cookie
    image: domoniquesmarthome/alexa-cookie-cli:latest
    restart: unless-stopped
    environment:
      - ALEXA_PROXY_HOST=domonique.local
      - ALEXA_PROXY_PORT=8888 
    volumes:
      # Path to alexa_remote_control.sh file that will be updated with REFRESH_TOKEN
      - [path-to-alexa_remote_control.sh]:/data/alexa_remote_control.sh
    ports:
      - 8888:8888